### PR TITLE
Add: Ace Css Art

### PR DESCRIPTION
**Pull request by nnh242**

### CODE REVIEW

**Comment by abdus** [comment]
@nnh242, Please remove `.DS_Store`. This file is creating a merge conflict.

**Comment by nnh242** [comment]
I have removed the .DS_store files by using the commands 
find . -name .DS_Store -print0 | xargs -0 git rm -f --ignore-unmatch 
and rm .DS_Store
I also added .DS_Store to gitignore and committed the changes. 
 Would that be okay now? Should I make a new pull request? Is there any other steps I can take? 
Thank you for your help.

**Comment by abdus** [comment]
There are still some conflicts, @nnh242. Sync your fork with remote repository. Here's how you can do it https://help.github.com/articles/syncing-a-fork/

**Comment by nnh242** [comment]
Thank you so much for your help. That has worked. I see that the branch has no conflicts now.

**Pull request merged**
